### ISSUE TITLE
Cannot install, PyBlueZ-0.22

### ISSUE THREAD

**Issue by rechardcollins** [pybluez/pybluez#100]
After installed python 3.4.3 and set the environment variables (modify path and add pythonpath).
Then run "PyBluez-0.22.win32-py3.4.exe". 
But A window message appears saying:
 "Python version 3.4 required, which was not found in the registry."

How can I install PyBluez correctly?
?????? 

Thanks.

**Comment by karulis** [comment]
Hi

Are You sure that You are using python 32 bit?

**Comment by rechardcollins** [comment]
My system :
Windows 10 (64 bit)
Python 3.4.3 (64 bit)

**Comment by rechardcollins** [comment]
Thanks.
After installing Python 3.4.3 (32bit, windows x96 MSI installer), I have installed the pybluez successfully.
