### ISSUE TITLE
Running inquiry.py on OSX causes segmentation fault

### ISSUE THREAD

**Issue by karulis** [pybluez/pybluez#103]
I will attach log
##

**Comment by karulis** [comment]
crash log file:
https://gist.github.com/karulis/00bed5489cb69b09e073

**Comment by cspensky** [comment]
I've seen this as well, but am having trouble replicating it reliably.  Let me know if you have any advice for replicating it, and I'd happily help track it down.

**Comment by karulis** [comment]
I have updated OSX to 10.11.4 and pyobjc to 3.1.1
and the issue seems to be solved
Let me know if it still happens for You

**Comment by mdiviesti** [comment]
I'm on OSX 10.12.6
Python 3.6.2 (installed with brew)
I downloaded PyBlueZ master then changed setup.py to use python3. 
ran setup.py. 

pyobjc-core 3.2.1

Running the sample with this line: 
nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, flush_cache=True, lookup_class=False)

I get a segment fault as described by the original ticket. 
If I remove lookup_class=False argument, it runs fine and discovers my devices (every single time without issue). Which is weird considering that lookup_class default is false in the method to begin with. I'm not sure why this would be an issue but it is.

**Comment by Doophie** [comment]
Im having this issue now

**Comment by rgov** [comment]
@Doophie This issue was last updated 2.5 years ago, please file a new issue.
