### ISSUE TITLE
can bluetooth.read_local_bdaddr() work for Windows ?

### ISSUE THREAD

**Issue by thomasleveil** [pybluez/pybluez#105]
I'm trying to make the _read-local-bdaddr.py_ example work in Windows with no luck.

Is there anything that can be done or is this example for Linux only?

**Comment by karulis** [comment]
Hi Thomas,

Are You using latest github version or the one drom PyPi?
Support fot that functionality was not yet released, but its in latest development version on github

**Comment by thomasleveil** [comment]
That's it! It is indeed working on Windows XP using the latest code from the master branch. Thank you
