### ISSUE TITLE
service.discover(2) - no documentation?

### ISSUE THREAD

**Issue by mstekker** [pybluez/pybluez#109]
Hi,

Thank you very much for this great wrapper!

I am to stupid to find any BLE API documentation. Can anybody help me by telling what the parameter for the function "service.discover()"  means? The example uses "2" as parameter.

Thanks in advance,

Mart.

**Comment by karulis** [comment]
Well thats the timeout - "2" means it will run for 2 seconds.
Yes documentation could be updated, any help would be appreciated:)

**Comment by mstekker** [comment]
Thanks! I will dig into the docs... if I am able I certainly will help!
