### ISSUE TITLE
from bluetooth.ble import DiscoveryService causes GTK to crash

### ISSUE THREAD

**Issue by mstekker** [pybluez/pybluez#110]
Hi,

After adding:
from bluetooth.ble import DiscoveryService

my GTK / Glade application crashes. This is happening during the initialization at a point where nothing calls the DiscoveryService. The GUI does not show up anymore.  The following is also imported:

import sys
import datetime
import os
import subprocess
from gi.repository import Gtk, GLib, GObject
import ConfigParser
from bluetooth.ble import DiscoveryService

Without GTK (just console) all is working fine. Any suggestions what could be the cause?

Extra information from console:

(test.py:8595): Gdk-ERROR **: The program 'test.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 147 error_code 2 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

I saw the BTLE module needs som c compiled stuff when installing, maybe that is the cause.

**Comment by mstekker** [comment]
Update:

gattlib causes this issue. workaround: let the pygtk program call another python script (subprocess) which runs the discovery. This second script may not import any pygtk related modules. Not the best solutions - but it woks.

**Comment by karulis** [comment]
I will close the issue and open one in gattlib. Thanks for reporting
