### ISSUE TITLE
pybluez installation error

### ISSUE THREAD

**Issue by frank123yang** [pybluez/pybluez#112]
Hi karlis
I am trying to install pybluez library but it fails all the time.when I run the Setup.py in CMD on Windows.It send a messge below.Could you give me some advices?
I am looking forward to your reply.
![image](https://cloud.githubusercontent.com/assets/12643448/13344489/69d02bfe-dc91-11e5-88b2-caf92b4ca3f0.png)

**Comment by karulis** [comment]
Hi,
Do You need to build it or just to install it?
If just install then try installers from pypi:
https://pypi.python.org/pypi/PyBluez

**Comment by karulis** [comment]
Closing
