### ISSUE TITLE
settimeout method for BluetoothSocket

### ISSUE THREAD

**Issue by johnliu55tw** [pybluez/pybluez#114]
Hello :D,

I want to set a time limit for connect() method cause sometimes it just take weird long time, and the one comes to my mind is the settimeout() method. However, here's what I encountered:

If the device is unable to be connected within the time limit set by settimeout(), BluetoothError exception with "timed out" message throws, which is fine. 

But, if the device is connected within the time limit, BluetoothError exception with "(77, 'File descriptor in bad state')" throws.
How do I know it's connected? Cause even though an exception throws, still I can use recv() and send() to communicate with the device.

Is this a bug? Or is there any other way to set the timed out property?

Thanks :P
##

**Comment by karulis** [comment]
You probably could try solution from c and use select for that:
http://stackoverflow.com/questions/2597608/c-socket-connection-timeout

But I will take a look how it works
