### ISSUE TITLE
Does pybluez have an ability to send passcode before connect to the Mac OS device?

### ISSUE THREAD

**Issue by itdxer** [pybluez/pybluez#116]
I caught an exception after I had written passcode in Mac.

```
socket.connect((host, port))
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: (13, 'Permission denied')
```

I don't see this feature and some clues would be really helpful.

**Comment by sunyu912** [comment]
I am having the same issue. Is it possible to configure the passcode using pybluez for pairing?

**Comment by itdxer** [comment]
@sunyu912 I didn't find a right way to do it and later I just gave up and did pair between devices manually using some command-line tool for bluetooth that had this feature.

**Comment by sunyu912** [comment]
Thanks @itdxer That's what I did too.
