### ISSUE TITLE
interrupt accept call

### ISSUE THREAD

**Issue by egorf** [pybluez/pybluez#120]
Hi!

Is there a way to interrupt the blocking accept call in the RFCOMM server code?

Say, I run this an a separate process:
`client_socket, client_info = server_socket.accept()`

I end up waiting for a connection, before I can go any further. Is there a good way to stop waiting for the connection?

**Comment by karulis** [comment]
It seems to be possible.
First You need to listen for incoming connections and then use select, some examples in C
http://stackoverflow.com/questions/3444729/using-accept-and-select-at-the-same-time
http://www.lowtek.com/sockets/select.html

**Comment by egorf** [comment]
This is not possible via PyBluez then?

[There does not seem to be](https://pybluez.googlecode.com/svn/www/docs-0.7/public/bluetooth.BluetoothSocket-class.html#listen) a `select()` or `poll()` method.

**Comment by karulis** [comment]
There is a select in python:
https://docs.python.org/3.5/library/select.html
it should work fine with pybluez

**Comment by muelli** [comment]
> Say, I run this an a separate process:

You mean a separate thread?

> Is there a way to interrupt the blocking accept call in the RFCOMM server code?

Shouldn't close()ing the socket (from a different thread) make the accept() return?
