### ISSUE TITLE
There is an IOError but the message is messy

### ISSUE THREAD

**Issue by yjcn** [pybluez/pybluez#122]
Traceback (most recent call last):
  File "E:/python/Btgui/Gui.py", line 31, in run
    nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, flush_cache=True, lookup_class=False)
  File "C:\Python27\lib\site-packages\bluetooth\msbt.py", line 15, in discover_devices
    devices = bt.discover_devices(duration=duration, flush_cache=flush_cache)
IOError: û�п��õ������ˡ�

My OS is Windows 10 Pro Simplified Chinese
And my code is using utf-8

**Comment by karulis** [comment]
This log is copied directly from command line(cmd) window?
Can You Try to log it into file and check weather it is still messy?

**Comment by yjcn** [comment]
I run it in cmd and the error message is Chinese "没有可用的数据了 " (GBK) It means there is no useful data.I want to know why the error happens and how fix it.
Mycode (QtCore.QThread):
    def run(self):
        print 'start thread'
        while not self.thread_stop:
            print 'scanning'
            try:
                nearby_devices = bluetooth.discover_devices(
                    duration=8, lookup_names=True, flush_cache=True, lookup_class=False)
            except IOError,e:
                print 'Error',e
            finally:
                for addr, name in nearby_devices:
                    self.emit(QtCore.SIGNAL('send'),addr,name)

**Comment by karulis** [comment]
Have You tried running inquiry.py?

**Comment by yjcn** [comment]
Yes. And I know why the error happens.When there is no device found, the IOError happens.

**Comment by karulis** [comment]
Well this is error reported by OS.
I dont think we can do much about it

**Comment by yjcn** [comment]
Well.Thanks for your reply. : )
