### ISSUE TITLE
IOError: A socket operation was attempted to an unreachable network.

### ISSUE THREAD

**Issue by 727yubin** [pybluez/pybluez#126]
I am trying to use pybluez to communicate with a wii remote (with the help of these 2 sites http://turpif.github.io/python/wiimote/bluetooth/2014/03/15/python-wiimote.html and https://people.csail.mit.edu/albert/bluez-intro/x232.html)
My simple code is the following:
import bluetooth
devices = bluetooth.discover_devices(lookup_names=True)

Then I get a long list. I find the mac address of my wii remote(E8:4E:**:**:**:**)

After that I do:
sock = sock=bluetooth.BluetoothSocket( bluetooth.RFCOMM )
sock.connect(('E8:4E:**:**:**:**', 1))

The output is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\bluetooth\msbt.py", line 72, in connect
    bt.connect (self._sockfd, addr, port)
IOError: A socket operation was attempted to an unreachable network.

I tried doing sock.connect() to my phone, and it works perfectly(It did ask for a pin, and after I typed it the bluetooth icon in the bottom right popped up and asked me to type the pin).

I have also tried using different ports, but no difference.

How should I fix it?
##

**Comment by karulis** [comment]
Have You try connecting wii to PC:
http://www.instructables.com/id/How-To-Connect-your-Wiimote-to-your-PC-via-Blueto/step2/Connecting-your-Wiimote/
