### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by matbeedotcom** [pybluez/pybluez#127]
I can't seem to find any documentation anywhere?

**Comment by FynnMazurkiewicz** [comment]
It is located [here](http://htmlpreview.github.io/?https://github.com/karulis/pybluez/blob/master/docs/index.html). 
Have you checked the Wiki yet? It says right in there ;) 
But the docs are broken anyways, see #97 .
You may however `git clone` them. They are at https://github.com/karulis/pybluez/tree/master/docs.
