### ISSUE TITLE
ImportError: No module named _bluetooth

### ISSUE THREAD

**Issue by bit111** [pybluez/pybluez#138]
Hello,
I am trying to run _PyBluez-0.20\examples\advanced\inquiry-with-rssi.py_ on Windows 7 but appears the error

```
Traceback (most recent call last):
  File "inquiry-with-rssi.py", line 7, in <module>
    import bluetooth._bluetooth
ImportError: No module named _bluetooth
```

I am interested in make some experiments with bluetooh proximity :)
##

**Comment by bwheel** [comment]
I get the exact same error. I am running windows 10. I am using visual studio code for a text editor, and their python plugin to run the file.

**Comment by rounaksingh** [comment]
I think the example is intended for linux, not for windows.

**Comment by karulis** [comment]
Yep only linux is supported for BLE
https://github.com/karulis/pybluez/blob/master/README
Any contribution on Windows platform would be great
