### ISSUE TITLE
maybe https://pypi.python.org/pypi/PyBluez too old?

### ISSUE THREAD

**Issue by shimondoodkin** [pybluez/pybluez#140]
https://pypi.python.org/pypi/PyBluez has version from 2015
that does not contain local device address

I wish that nfc-bluetooth examples would work out of the box on Windows and Linux
https://github.com/nfcpy/nfcpy/blob/master/examples/handover-test-client.py
https://github.com/nfcpy/nfcpy/blob/master/examples/handover-test-server.py

**Comment by karulis** [comment]
I dont have much time right now for new release,
I plan to release it after python 3.6 release (3.6.0 final: 2016-12-16 )
so maybe by Christmas.

**Comment by RyuzakiKK** [comment]
@karulis do you have any news about that?

**Comment by vit1251** [comment]
I see on PyPi server actual version is 0.22 but does not understand current version and News page.
