### ISSUE TITLE
PORT_ANY crashes BluetoothSocket.connect()

### ISSUE THREAD

**Issue by otoomey** [pybluez/pybluez#150]
Passing `bluetooth.PORT_ANY` (equal to `0`) into `BluetoothSocket.connect()` throws an `'Invalid Argument'` exception. I am not sure if this is intended behaviour.

To reproduce:
```
import bluetooth
sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
sock.connect("00:16:BC:30:D8:76",bluetooth.PORT_ANY) #Exception is thrown on this line
```

**Comment by muelli** [comment]
I am surprised if that worked.  What do you want to achieve? I think the semantics of `PORT_ANY` that if you want to bind your socket to a port and you don't care which port it'll be. Then you can get the port the socket bound to with getsockname.
