### ISSUE TITLE
OSError: The handle is invalid. (Windows 10)

### ISSUE THREAD

**Issue by DelphicGaming** [pybluez/pybluez#155]
The Simple Script I Am Using Is
# Start Of Script
from bluetooth import *

nearby_devices = discover_devices(lookup_names=True)
print("found %d devices" % len(nearby_devices))

for addr, name in nearby_devices:
    print("  %s - %s" % (addr, name))

# End Of Script

And I'm Seeming To Get 
devices = bt.discover_devices(duration=duration, flush_cache=flush_cache)
OSError: The handle is invalid.

I Don't Know Why And I've Tried Asking Other People And They Have NO Clue. (Yes It Did Successfully Install)

I'm Using Windows 10 (64 bit) With Python 3.4.3 (32 bit)

Any Help Would Be Appreciated

**Comment by rsmssnpdr** [comment]
Having just had this issue, the problem seems to be in windows.

My personal solution was to plug the USB bluetooth dongle into a USB 3.0 port. The 2.0 ports do not show the dongle as connected.
