### ISSUE TITLE
lookup_names of find_devices() doesn't work with Python 3

### ISSUE THREAD

**Issue by RyuzakiKK** [pybluez/pybluez#159]
The function `find_devices()` with the attribute lookup_names setted to True doesn't work with Python 3.

For example executing `asynchronous-inquiry.py` with Python 3 will always terminate with an empty list of devices found.
But if you change `d.find_devices(lookup_names = True)` to `d.find_devices(lookup_names = False)` the search will work as it should.

This problem is not present with Python 2.

**Comment by rgov** [comment]
Hi @RyuzakiKK, did you ever figure out the root cause of this?
