### ISSUE TITLE
Only args[0] of BluetoothError is filled

### ISSUE THREAD

**Issue by RyuzakiKK** [pybluez/pybluez#166]
Executing this snippet here:

```
from bluetooth import BluetoothSocket, BluetoothError, RFCOMM

try:
    client_socket = BluetoothSocket(RFCOMM)
    client_socket.setblocking(False)
    client_socket.connect(("AA:BB:CC:DD:EE", 3))
except BluetoothError as be:
    print("Description: %s" % be.args[0])
    print("Error number: %s" % be.errno)
    print("Filename: %s" % be.filename)
    print("Strerror: %s" % be.strerror)
```

The output is something like the following:

```
Description: (16, 'Device or resource busy')
Error number: None
Filename: None
Strerror: None
```

The expected result is that the fields should not be None. For example right now to catch a particular error you need to parse the description field in order to get the error number, instead of just reading `errno` variable.

**Comment by rgov** [comment]
Hi @RyuzakiKK thanks for pointing this out. If you have the inclination to submit a patch, this seems like a good starter bug.
