### ISSUE TITLE
BLE scanning

### ISSUE THREAD

**Issue by pedrofelipest** [pybluez/pybluez#169]
Is there a limit to how many devices the scan can return?

Sometimes, when you have too many devices nearby, it does not return all of them in the tuple.

**Comment by FynnMazurkiewicz** [comment]
There is no theoretical limit and I find your observation very surprising.
How many devices are 'too many'?

The BLE-Scan example currently uses `pygattlib`, which you can find [here](https://bitbucket.org/OscarAcena/pygattlib), and as far as I can tell, they don't face a practical limit either. If you have less than 30~ish advertising devices around you, this **really** shoulnd't be an issue.

Are you sure that all devices support BLE and are advertising when you're running the scan?
