### ISSUE TITLE
Installation dependency broken on Python 3

### ISSUE THREAD

**Issue by vit1251** [pybluez/pybluez#173]
When use 

```pip install pybluez```

And start using example about low energy example, we have:

```
Traceback (most recent call last):
  File "./b2.py3", line 7, in <module>
    from bluetooth.ble import DiscoveryService
  File "/usr/local/lib/python3.5/dist-packages/bluetooth/ble.py", line 1, in <module>
    from gattlib import *
ImportError: No module named 'gattlib'
```

Require additional install dependencies but on modern system we receive:

```
t_python-py34 -lboost_thread -lbluetooth -o build/lib.linux-x86_64-3.5/gattlib.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lboost_python-py34
    /usr/bin/ld: cannot find -lboost_thread
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```

It expected on Python 3.5 or 3.6 on machine without boost.

**Comment by FynnMazurkiewicz** [comment]
Confirmed on Ubuntu 16.04. This is definitely down to gattlib.
Following [their own install instructions](https://bitbucket.org/OscarAcena/pygattlib/src/45e04060881a?at=default) doesn't work either.
 The debian repository installation also failed, I haven't tried a source install.

Edit: There also are some pending PR's over on their BitBucket. [This one](https://bitbucket.org/OscarAcena/pygattlib/pull-requests/22/python-3-minor-version-adaptation-for/diff#comment-None) would fix your issue. So right now, you'd have to install from source and change the offending line yourself.

**Comment by avcatshy** [comment]
install these depends first,
```
pkg-config
libboost-python-dev
libboost-thread-dev
libbluetooth-dev >= 4.101
libglib2.0-dev
python-dev
```
then, for gattlib with python3, have a try with :
```
pip3 download gattlib
tar xvzf ./gattlib-0.20150805.tar.gz
cd gattlib-0.20150805/
sed -ie 's/boost_python-py34/boost_python-py35/' setup.py
pip3 install .
``` 
good luck! 👍

**Comment by asaladino** [comment]
I using ubuntu and had python 3.7 install. What worked for me was, when ran
`ldconfig -p | grep libboost_python`

I noticed that the boost library ended with `_python37` so that is what I used.

```
	libboost_python37.so.1.67.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libboost_python37.so.1.67.0
	libboost_python37.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libboost_python37.so
	libboost_python27.so.1.67.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libboost_python27.so.1.67.0
	libboost_python27.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libboost_python27.so
```

So I ran 

```
sed -ie 's/boost_python-py34/boost_python37/' setup.py
pip3 install .
```

Then followed up with `pip3 install pybluez\[ble\]`

**Comment by vladyslav2** [comment]
For everyone who still use an issue
```
sudo apt-get install libbluetooth-dev
sudo apt-get install libboost-python-dev
sudo apt-get install libboost-all-dev
git clone https://github.com/pybluez/pybluez
cd pybluez
pip3 install .
```
