### ISSUE TITLE
"bind()" does not work on OSX

### ISSUE THREAD

**Issue by gobftald** [pybluez/pybluez#186]
I closed this issue since it had already escalated in #174 
please read my findings below as additional information to #174 

fresh OSX installation
fresh Xcode
fresh python 2.7 virtualenv
newest pybluez cloned and installed from git

running the simplest test code:
from lightblue import *
s = socket()
s.bind(("", 0))          >> gives error

as a result of some quick debugging:
the problem is in the _getavailableport() call,
at the BBServiceAdvertiser.addRFCOMMServiceDictionary.... pyobjc function, which raises an exception

BBServiceAdvertiser comes from _LightAquaBlue which module tries to load/import LightAquaBlue.framework but it fails, so BBServiceAdvertiser and its functions don't exist at all and give that exception

maybe the problem has some other roots, but during initialization of LightAquaBlue framework initFrameworkWrapper() tries to use/load BridgeSupport mechanism, but the directory from where it tries to load is hardcoded in _bridgesupport.py, so it cannot find LightAquaBlue.bridgesupport XML file although it exists in my installed lightblue directory tree of my virtualenvs

I tried to patch and extend hardocoded BRIDGESUPPORT_DIRECTORIES list with the proper path of the LightAquaBlue.bridgesupport XML file  installed by pybluez into my virtualenv,
as a result the original error disappeared, so BBServiceAdvertiser.addRFCOMMServiceDictionary... call didn't raise an exception, but it did not run properly giving error return value

I checked initFrameworkWrapper() again and it turned out that based on LightAquaBlue.bridgesupport XML file it tried to load LightAquaBlue's dynamic library as well but did not find it,
there is also a binary file without extension in the directory tree of LightAquaBlue framework which is likely this dynamic library but far from the relative postion where loader/importer tries to find it

I stoppped debugging since it shows some general problem with the installation of lightblue and its LightAquaBlue framework which is necessary for "bind()" function.
I know that bridgesupport mechanism was depreciated, so e.g. IOBluetooth framework was loaded by ObjCLazyModule in the curent code, but I have not find any other mechanism trying to import/load BBServiceAdvertiser in another way

I hope you have some ideas or solution
gobftald

**Comment by rgov** [comment]
Please post your solution if you found one, for others.
