### ISSUE TITLE
Descriptor in Bad State

### ISSUE THREAD

**Issue by faxe1008** [pybluez/pybluez#191]
Hi,

I am trying to connect a HC-06 module using bluetooth, which is already paired with my device.
```
self.bluetooth_socket = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
self.bluetooth_socket.connect(("MAC", 1))
```

and I am getting this error:
```
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (77, 'File descriptor in bad state')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raspberrypi_code/BlueMQTTBroker.py", line 201, in <module>
    bluetooth_socket.connect((client.mac_address, client.port))
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: (77, 'File descriptor in bad state')
```
I am really confused as to why that happens - a few weeks ago that worked just perfectly.

**Comment by faxe1008** [comment]
It seems like this was caused by setting using `self.bluetooth_socket.settimeout(5)` removing it solves the problem however I need to set the timeout :^)

**Comment by btashton** [comment]
@faxe1008 can you try setting the timeout via the normal socket class, I have run into a few issues recently with the BluetoothSocket class and am trying to debug it.
```
import socket

self.bluetooth_socket = bluetooth.BluetoothSocket(bluetooth.RFCOMM)

_sock = socket.fromfd(self.bluetooth_socket.fileno(), 31, 1, 3)
_sock.settimeout(5)
_sock.close()

self.bluetooth_socket.connect(("MAC", 1))
```

**Comment by 0xffset** [comment]
I think that this issue occurs when we try to set the variables connections `bluetooth_socket.connect(('3C:91:80:C9:7C:56', 3))`. **Try to parser it.**

**Comment by hoangesoftblog** [comment]
For those who looking for this problem, it is probably because the socket is already closed (by timeout, as someone mentioned above, or accidentally closed by calling socket.close()) when it connects to the address and the port. Create new socket helps solve that problem in my case.
