### ISSUE TITLE
Can you fit PyBluez to python3.6?

### ISSUE THREAD

**Issue by EthanGD** [pybluez/pybluez#199]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System: Windows 10
 - **Hardware: external Bluetooth adaptor
 - **PyBluez Version: 0.22

## Issue

Hi dear sir, I have a problem when i am installing pybluez 0.22 by python3.6
How regrettable it is, can you master fit it to python3.6
Thank you so much.

**Comment by c-w** [comment]
What problem exactly are you facing running the library on Python 3.6 on Windows 10? I've written up some installation hints here: https://github.com/pybluez/pybluez/issues/180#issuecomment-408235161, perhaps these steps can help you?
