### ISSUE TITLE
Race condition in _get_available_port

### ISSUE THREAD

**Issue by Arusekk** [pybluez/pybluez#202]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** Linux
 - **Hardware:** external Bluetooth adaptor
 - **PyBluez Version:** latest (0.18)

## Issue

Please provide information necessary to reproduce the issue, including sample
code.

If you have long logs, please post them on https://gist.github.com and link to
the Gist here.

The issue is version-independent, and it is as follows:

1. An instance of python tries to bind to a specified address with PORT_ANY.
2. The function `_get_available_port` returns some unused port for it.
3. Someone (possibly a different python instance, or any other program) binds successfully to the port we wanted to bind to.
4. Then we try to bind to it, and execution fails.

A simple example:
```py
import bluetooth, os, subprocess

src_addr = subprocess.check_output(["hcitool", "dev"]).split()[-1]
os.fork()

sock = bluetooth.BluetoothSocket(bluetooth.L2CAP)
sock.bind((src_addr, 0))
```

Expected exception in at least one instance:
```py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    sock.bind((src_addr, 0))
  File "/usr/lib64/python2.7/site-packages/bluetooth/bluez.py", line 140, in bind
    return self._sock.bind (addrport)
_bluetooth.error: (98, 'Address already in use')
```
Same with `proto=bluetooth.RFCOMM`

**Comment by rgov** [comment]
I think there's always going to be the opportunity to race between the time when `_get_available_port` picks a port number and then binds to it, but maybe it should do port numbers in random order rather than starting from 0x1001 every time.

Would you be willing to send a pull request for that?

**Comment by Arusekk** [comment]
I think the proper solution for this would be to look for the port in a loop inside `bind()`.
I'm assuming that one can bind multiple times if the previous attempts yielded "Address already in use" (works on my box).

This could be something like:
```py
from errno import (EADDRINUSE, EBUSY, EINVAL)
# ...

def _get_available_ports(protocol):
    if protocol == RFCOMM:
        return range (1, 31)
    elif protocol == L2CAP:
        return range (0x1001, 0x8000, 2)
    else:
        return [0]

class BluetoothSocket:
    # ...
    def bind (self, addrport):
        addr, port = addrport
        if port != 0:
            try:
                return self._sock.bind (addrport)
            except _bt.error as e:
                raise BluetoothError (*e.args)
        for port in _get_available_ports (self._proto):
            try:
                return self._sock.bind ((addr, port))
            except _bt.error as e:
                err = BluetoothError (*e.args)
                if e.errno != EADDRINUSE:
                    break
        raise err
```

**Comment by Arusekk** [comment]
Made a pull request for this (#203)
