### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ghost** [pybluez/pybluez#210]
Hello everyone

This is a question more than an issue but I'll ask anyway.
The 'issue' I'm having is that can't detect more than two devices over a 30 seconds scan, whereas with other tools the results are much different. Bluetoothctl detects upwards of 10 devices and Blue Hydra detects between 20 and 30 in my vicinity including cars and wearables.
So the question is: am I doing something wrong? Is this an inherently limited solution? How are those other solutions way more powerful than this? And lastly is there any alternative library to pybluez?

By the way the code I'm using is literally just the example provided in the wiki.

Thanks everyone for the info

**Comment by rgov** [comment]
Please provide information about your operating system and hardware.

**Comment by ghost** [comment]
@rgov I'm using linux Mint 19 with the Sena UD100 adapter (with a bigger antenna) and I disabled the default bluetooth card in the bios to make sure that everything that needs bluetooth actually uses the dogle.
