### ISSUE TITLE
pybluez throws exceptions when call find_services

### ISSUE THREAD

**Issue by vlovich** [pybluez/pybluez#213]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** OSX 10.13.6
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.) N/A
 - **PyBluez Version:** master (bf9aa43 )

## Issue
```
import bluetooth


  services = bluetooth.find_service(address="all")
  for svc in services:
    print("Service Name: %s"    % svc["name"])
    print("    Host:        %s" % svc["host"])
    print("    Description: %s" % svc["description"])
    print("    Provided By: %s" % svc["provider"])
    print("    Protocol:    %s" % svc["protocol"])
    print("    channel/PSM: %s" % svc["port"])
    print("    svc classes: %s "% svc["service-classes"])
    print("    profiles:    %s "% svc["profiles"])
    print("    service id:  %s "% svc["service-id"])
    print("")
```

```
Traceback (most recent call last):
  File "python-env/lib/python3.7/site-packages/PyBluez-0.22-py3.7.egg/lightblue/_lightblue.py", line 76, in findservices
    lastseen = iobtdevice.getLastServicesUpdate()
AttributeError: 'NoneType' object has no attribute 'getLastServicesUpdate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./record.py", line 18, in <module>
    find_services()
  File "./record.py", line 5, in find_services
    services = bluetooth.find_service(address="all")
  File "python-env/lib/python3.7/site-packages/PyBluez-0.22-py3.7.egg/bluetooth/macos.py", line 49, in find_service
    dresults = lightblue.findservices(addr=address, name=name)
  File "python-env/lib/python3.7/site-packages/PyBluez-0.22-py3.7.egg/lightblue/_lightblue.py", line 107, in findservices
    iobtdevice.closeConnection()
AttributeError: 'NoneType' object has no attribute 'closeConnection'
```

**Comment by rgov** [comment]
Did you install the latest version from Git?

It looks like whatever sets the variable `iobtdevice` is failing. Do you have the capacity to try to debug why that is?

**Comment by vlovich** [comment]
Latest version from git yes.  Happy to try to debug if you point me in the direction of where I should look.

**Comment by rgov** [comment]
This line is probably what's failing: https://github.com/pybluez/pybluez/blob/master/macos/_lightblue.py#L73

For whatever reason, it's not returning a good device. Can you add some print statements around it?

**Comment by vlovich** [comment]
iobtdevice = _IOBluetooth.IOBluetoothDevice.withAddressString_(devaddr)
printed right after: iobtdevice is None for all

**Comment by rgov** [comment]
What makes you think the string "all" should work?

**Comment by vlovich** [comment]
If I don't pass anything to find_services, I get:
iobtdevice is None for b'00:E1:8C:B2:9E:B2'

However, that's not a BT MAC addr for my adapater AFAICT (according to BT drop down menu) nor is it any device that I have paired.

**Comment by rgov** [comment]
I don't know. `00:E1:8C` is an Intel device.

**Comment by vlovich** [comment]
Ok.  So it seems like there just needs to be a check that if we fail to get the device we either explicitly raise an exception if addr is not None (i.e. requested explicit device) or skip if addr is None.

**Comment by rgov** [comment]
I think that makes sense, thanks. Can you please open a pull request?

**Comment by vlovich** [comment]
Done.
