### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by forderud** [pybluez/pybluez#221]
I'm currently trying to program my Divoom Timebox from Python. This unfortunately require a custom build of pybluez, since the latest 0.22 tag doesn't include https://github.com/pybluez/pybluez/pull/201.

Would it be possible for the maintainers of this project to publish a new tag/release, so that that recent improvements can "trickle down" to the various python distributions?

**Comment by rgov** [comment]
Yes, we do need to do it. Dupe of #212 probably.

What platform are you using? It shouldn't be really that hard to install a new build of pybluez, except on Windows 10 it seems difficult.

```
pip install --upgrade git+https://github.com/karulis/pybluez.git
```

might work for you?

**Comment by rgov** [comment]
Yes, we do need to do it. Dupe of #212 probably.

What platform are you using? It shouldn't be really that hard to install a new build of pybluez, except on Windows 10 it seems difficult.

```
pip install --upgrade git+https://github.com/karulis/pybluez.git
```

might work for you?

**Comment by forderud** [comment]
I'm using Windows 10 (x64).

**Comment by HeyITGuyFixIt** [comment]
> ```
> pip install --upgrade git+https://github.com/karulis/pybluez.git
> ```
I tried this on Windows 7 and it successfully installed it. Python 3.7.2
