### ISSUE TITLE
Setup fails to compile LightAquaBlue and install pybluez

### ISSUE THREAD

**Issue by eduardomarossi** [pybluez/pybluez#222]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System: macOS High Sierra**
 - **Hardware: Macbook Air 2018** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **Python Version: 3.7 (brew)**
 - **PyBluez Version: Git - commit: bfaff35 **

## Issue

Please provide information necessary to reproduce the issue, including sample
code.

Setup fails to compile LightAquaBlue project (as log indicates).

https://gist.github.com/eduardomarossi/53856bcaf533be849d0f5478b3ec4fc9

I think the problem is when it tries to copy InfoPlist.strings file on non-US macOS.
I opened the project and removed the InfoPlist.strings from the Build Phases - Copy Bundle Resources and the project compiled/installed successfully.  although, I think the proper fix is something with the (localization) variable (I don't know much about Xcode).

After fixing that, I could install using pip3 install git+repo
Here is my forked repo working (based on bfaff35 commit): https://github.com/eduardomarossi/pybluez

Thanks,
Eduardo Marossi

**Comment by rgov** [comment]
Great, thanks for resolving this problem. Can you open up a pull request instead of an issue, so we can merge changes more easily?
