### ISSUE TITLE
CSR 4.0 USB dongle and Windows 7

### ISSUE THREAD

**Issue by rajkovicbojan** [pybluez/pybluez#225]
Is it possible to use CSR 4.0 usb dongle and windows 7 with pybluez libary?

**Comment by rgov** [comment]
It is unlikely that anyone has any specific experience with this combination. If it works as a regular Bluetooth adapter in Windows, it will probably work in PyBluez. It looks like it's less than $8 so feel free to try it and file a bug if it does not work.
