### ISSUE TITLE
it is unable to install pybluez in linux which shows gcc compilation error because of the missing bluetooth header file.

### ISSUE THREAD

**Issue by justinepdevasia** [pybluez/pybluez#236]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System: ubuntu 18**
  - **Python Version: python3**
 - **PyBluez Version: 0.22**

## Issue
while using the command pip3 install **pip install PyBluez** it shows the following error
In file included from bluez/btmodule.c:20:0:
    bluez/btmodule.h:5:10: fatal error: bluetooth/bluetooth.h: No such file or directory
     #include <bluetooth/bluetooth.h>
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by justinepdevasia** [comment]
it can be  solved by using the command
                           :      **sudo apt-get install libbluetooth-dev**

**Comment by santosjose7** [comment]
thank you for this
