### ISSUE TITLE
I can not install module

### ISSUE THREAD

**Issue by 112kutiko** [pybluez/pybluez#238]
System
 Operating System: win10
 Hardware:laptop Bluetooth adaptor
 Python Version: 3.7.1
 PyBluez Version:PyBluez-0.22

I can not install module
```
(base) C:\Users\tadas>pip install PyBluez
Collecting PyBluez
  Using cached https://files.pythonhosted.org/packages/c1/98/3149481d508bee174335be6725880f00d297afebe75c15e917af8f6fe169/PyBluez-0.22.zip
    Complete output from command python setup.py egg_info:
    Could not find the Windows Platform SDK

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\tadas\AppData\Local\Temp\pip-install-94cp_bzc\PyBluez\
```

**Comment by BlackFrog1** [comment]
Duplicate issue #180.  Possibly solution in the comment @ https://github.com/pybluez/pybluez/issues/180#issuecomment-397547920 and https://github.com/pybluez/pybluez/issues/180#issuecomment-397891422
