### ISSUE TITLE
Please adapt the iOS platform

### ISSUE THREAD

**Issue by lenbobopp** [pybluez/pybluez#239]
@@*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:IOS
 - **Hardware:IOS internal Bluetooth adaptor
 - **Python Version:3.6.1
 - **PyBluez Version: latest

## Issue

I installed Pythonista3 on IOS device and accessed the PyBluez by StaSh. It says this platform(iOS)  is currently not supported by PyBluez 

![IMG_C1F3272F273C-1](https://user-images.githubusercontent.com/31583080/56709097-1e02f400-6752-11e9-9547-b92bac15fcf7.jpeg)

**Comment by stonehippo** [comment]
@lenbobopp Pythonista ships with the `cb` module for BLE support, which is a wrapper for the Core Bluetooth library. There’s no open developer access for Bluetooth Classic in iOS, so Pythonista can’t use it (this requires the ExternalAccessory API).

**Comment by rgov** [comment]
Here's the [cb](http://omz-software.com/pythonista/docs/ios/cb.html#module-cb) module.

I'm going to close this, thanks for the answer @stonehippo.
