### ISSUE TITLE
Set up Read the Docs

### ISSUE THREAD

**Issue by rgov** [pybluez/pybluez#249]
Tagging @beadysea here.

Read the Docs cannot generate documentation from this repo. Here is the error log:

https://readthedocs.org/projects/pybluez/builds/9413084/

It expects a file called `contents.rst`.

**Comment by beadysea** [comment]
Thanks, I'm on it.

**Comment by rgov** [comment]
Weird, the content isn't visible at https://pybluez.readthedocs.io/en/latest/ but the PDF looks good: https://buildmedia.readthedocs.org/media/pdf/pybluez/latest/pybluez.pdf

**Comment by rgov** [comment]
Just caching issues maybe. I think it works!

**Comment by beadysea** [comment]
It works, did an F5 refresh on my browser.

**Comment by beadysea** [comment]
@rgov can you update the doc link on the repo from https://pybluez.github.io/  to https://pybluez.readthedocs.io
