### ISSUE TITLE
Add a new release to PyPI

### ISSUE THREAD

**Issue by cclauss** [pybluez/pybluez#255]
https://pypi.org/project/PyBluez was last updated in 2015.

*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:**
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **Python Version:**
 - **PyBluez Version:**

## Issue

Please provide information necessary to reproduce the issue, including sample
code.

If you have long logs, please post them on https://gist.github.com and link to
the Gist here.

**Comment by rgov** [comment]
Yes, we have some issues tracking this, e.g., #233, #212, #180.
