### ISSUE TITLE
Contrib sap_client.py is not Python 3 compatible

### ISSUE THREAD

**Issue by cclauss** [pybluez/pybluez#263]
Discovered in #254 - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/test/sap_client.py contains legacy __print__ statements that need to be converted to __print()__ function to be Python 3 compatible.  To find other potential compatibility issues, please run the following on that codebase:
* __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__

@holtmann

*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:**
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **Python Version:**
 - **PyBluez Version:**

## Issue

Please provide information necessary to reproduce the issue, including sample
code.

If you have long logs, please post them on https://gist.github.com and link to
the Gist here.

**Comment by rgov** [comment]
Hm, this needs to be filed against the upstream Bluez project.

**Comment by rgov** [comment]
Closing this because I don't think we control it.
