### ISSUE TITLE
PBAP service

### ISSUE THREAD

**Issue by mike-lt** [pybluez/pybluez#273]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System: Windows 10 x64
 - **Hardware:** Laptop Windows
 - **Python Version: 3.6.6
 - **PyBluez Version: 0.22

## Issue

Hi,

with one of the provided examples (sdp-browse.py) it is possible to get the list of the available services. 
Specifically, I want to retrieve datas (contacts, phone calls and sms) from two services (SMS/MMS and OBEX PhoneBook Access Server). 
These are the info of the two services I'm interested in:

Service Name: b'SMS/MMS\x00'
    Host:        xx:xx:xx:xx:xx:xx
    Description:
    Provided By: None
    Protocol:    RFCOMM
    channel/PSM: 4
    svc classes: [b'1132']
    profiles:    [(b'1134', 258)]
    service id:  None

Service Name: b'OBEX Phonebook Access Server\x00'
    Host:        xx:xx:xx:xx:xx:xx
    Description:
    Provided By: None
    Protocol:    RFCOMM
    channel/PSM: 5
    svc classes: [b'112f']
    profiles:    [(b'1130', 258)]
    service id:  None

I searched and tried all the libraries here (https://github.com/search?l=Python&q=pbap&type=Repositories
) but none of them works on windows. I tried nccgroup/nOBEX on Ubuntu and it works but I need something on windows.
Is it possible to do it with this library?

Thank you
Mark

**Comment by beadysea** [comment]
Hi @mike-lt,
The PyBluez library is an application programming interface (API) designed to provide python developers easy access to send and receive data over Bluetooth communication links. Part of this interface is the service discovery protocol (sdp) which identifies the services available on Bluetooth devices however PyBluez does not provide these services (such as OBEX or SMS). It is up to application programmers to develop applications supporting those services while possibly using PyBluez as the underlying communication link. Think of the application in layers:

|Application Layer| my phone app |
|:-----| :-------: |
|Services Layer | OBEX/SMS/MMS|
|Data link layer | PyBluez - Comm link (RFCOMM) |

Your idea sounds very interesting and I wish you every success in finding or developing a solution.
