### ISSUE TITLE
pybluez can not work with Bluetooth device through Uart or USB.

### ISSUE THREAD

**Issue by barrychi** [pybluez/pybluez#283]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - Windows
 - Bluetooth Uart Device
 - 2.7.x
 - newest

## Issue

pybluez can not work with Bluetooth device through Uart or USB.
I mean I have a Bluetooth Uart device and connect it to windows.
I can use serial tool to communicate with this device.
I can not control this device through pybluez.

>>> import bluetooth
>>> bluetooth.discover_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\bluetooth\msbt.py", line 15, in discover_devices
    devices = bt.discover_devices(duration=duration, flush_cache=flush_cache)
IOError: The RPC server is unavailable.

**Comment by rgov** [comment]
@barrychi Do you expect this to work? If Windows sees your device as a regular Bluetooth controller, it should just work through the use of the Windows BT APIs. I don't know that we should have to handle anything special for this case.

If other parts of Windows Bluetooth are working as expected, then maybe its something we can fix in PyBluez.
