### ISSUE TITLE
Allow sending mutable bytes-like objects

### ISSUE THREAD

**Issue by dogtopus** [pybluez/pybluez#287]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** Linux, Windows ([widcomm-rfcomm](https://github.com/pybluez/pybluez/blob/30060cd07f625a24e4f47fe122f0acea54108dc8/widcomm/rfcommport.cpp#L264), [widcomm-l2cap](https://github.com/pybluez/pybluez/blob/30060cd07f625a24e4f47fe122f0acea54108dc8/widcomm/l2capconn.cpp#L275), [msbt](https://github.com/pybluez/pybluez/blob/30060cd07f625a24e4f47fe122f0acea54108dc8/msbt/_msbt.c#L272)) (could be more, further investigation needed)
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.) Any
 - **Python Version:** 3.8
 - **PyBluez Version:** master (30060cd)

## Issue

Trying to send a memoryview object using `BluetoothSocket.send()` API results in an exception which states that only read-only bytes-like objects are expected.

A quick look at the `bluez/btmodule.c` reveals that the method expects `s#` type args as the buffer. According to the python documentation `s#` only accepts read-only (non-mutable) str or bytes-like object i.e. practically only str and bytes. One way to resolve this is to switch to `s*` or `y*` so that the API also accepts mutable bytes-like objects (like memoryview).

**Comment by rgov** [comment]
Thanks for looking into the root cause of the issue. If you want to submit a pull request for this change, please test your solution and do so, and I will accept the change.

**Comment by dogtopus** [comment]
Looks like the Windows binding (both widcomm and msbt) have the same problem. They all accepts `s#` as the parameter for write/send method.

I'll send a PR for BlueZ binding soon. Fix for Windows binding might take a while since I need to make a test environment first.

UPDATE: Fixes for BlueZ and msbt are tested and pushed.
