### ISSUE TITLE
Segmentation fault via the methods `.get_l2cap_options()` and `.set_l2cap_mtu()`

### ISSUE THREAD

**Issue by b1ack0wl** [pybluez/pybluez#302]
**OS**: Linux Mint 19.3
**Version**: Latest from master

I'm working on a PR, but I wanted to at least file this bug to prevent duplicates from being submitted.
The following statements will cause a segmentation fault (I've only verified this on Linux, but this could trigger on other OS's as well)

```
import bluetooth

sock = bluetooth.BluetoothSocket(bluetooth.L2CAP)
sock.get_l2cap_options()
```
Attaching GDB shows that the crash is happening within `PyObject_Free` which is called via this statement here: https://github.com/pybluez/pybluez/blob/master/bluez/btmodule.c#L791.

Looking at the Python3 documentation for `_PyBytes_Resize` it says the following: `It is an error to call this function if the refcount on the input bytes object is not one.` This may be the issue? But who knows. Once I figure it out I'll submit a PR.

**Comment by rgov** [comment]
Thank you for working on a PR. I'll merge it when you've figured it out and it will make it into the next release.

**Comment by b1ack0wl** [comment]
I fixed it, but could someone else double check my work?

I changed the following statement in `btmodule.c`
 * `PyObject *buf = PyUnicode_FromStringAndSize((char *)NULL, buflen);`  --> ` PyObject *buf = PyBytes_FromStringAndSize((char *)NULL, buflen);` and the crash no longer happens. I also verified the syscall to `getsockopt` works fine via `strace`

**Comment by b1ack0wl** [comment]
PR Opened: https://github.com/pybluez/pybluez/pull/303
