### ISSUE TITLE
What is the version of pygattlib to use in windows for pybluez ?

### ISSUE THREAD

**Issue by theetechy** [pybluez/pybluez#328]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** Windows
 - **Hardware:** Intel(R) Wireless Bluetooth(R)
 - **Python Version:** 3.7.3
 - **PyBluez Version:**0.23

## Issue
What is the version of pygattlib to use in windows for pybluez ?
pip install pygattlib
Collecting pygattlib
  Using cached pygattlib-0.0.4.tar.gz (4.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\test\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\test~1\\AppData\\Local\\Temp\\pip-install-fq3sujj7\\pygattlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\test~1\\AppData\\Local\\Temp\\pip-install-fq3sujj7\\pygattlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\test~1\AppData\Local\Temp\pip-install-fq3sujj7\pygattlib\pip-egg-info'
         cwd: C:\Users\test~1\AppData\Local\Temp\pip-install-fq3sujj7\pygattlib\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\test~1\AppData\Local\Temp\pip-install-fq3sujj7\pygattlib\setup.py", line 54, in <module>
        raise OSError("Not supported OS")
    OSError: Not supported OS
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rgov** [comment]
I believe pygattlib is only available on Linux.
