### ISSUE TITLE
Where to find bluetooth._bluetooth module

### ISSUE THREAD

**Issue by NexusChak** [pybluez/pybluez#332]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System: macOS/Windows 10
 - **Hardware: Laptop/Desktop
 - **Python Version: Python 3.7.7
 - **PyBluez Version: 0.30

## Issue

In one of those advanced example, "inquiry-with-rssi.py", it imports a low level bluetooth wrapper:
`import bluetooth._bluetooth`
This seems to have the ability to get the live RSSI for a certain bluetooth device.
Unfortunately, I couldn't find this module anywhere.

**Comment by alessandro-allen** [comment]
_bluetooth can be built for your system by passing `install` to the setup.py script.
