### ISSUE TITLE
Error while installing pybluez-win10 downloaded and installed microsoft bulid tools 

### ISSUE THREAD

**Issue by BinaryBreaker** [pybluez/pybluez#339]
----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\mmh\pycharmprojects\untitled\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0]
 = '"'"'C:\\Users\\MMH\\AppData\\Local\\Temp\\pip-install-4rjv92ay\\pybluez-win10\\setup.py'"'"'; __file__='"'"'C:\\Users\\MMH\\AppData\\Local\\Temp\\pip-install-4
rjv92ay\\pybluez-win10\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compil
e(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MMH\AppData\Local\Temp\pip-record-rk1klyny\install-record.txt' --single-version-externally-managed -
-compile --install-headers 'c:\users\mmh\pycharmprojects\untitled\venv\include\site\python3.7\pybluez-win10' Check the logs for full command output.

**Comment by rgov** [comment]
Please don't just paste the console barf when you get an error. There was an issue template that you deleted, which asked for important information.  It is also impossible to read because you did not apply proper formatting.

**Comment by rgov** [comment]
Aside from that `pybluez-win10` is not an official library, try to just install `pybluez`.

**Comment by BinaryBreaker** [comment]
sorry for uploading the full console error detail but when i install the pybluez it give me an error when a try to connect a device
-------------------------------------'
Traceback (most recent call last):
  File "C:/Users/MMH/Desktop/new22.py", line 18, in <module>
    client_socket.connect((bd_addr,3))
  File "C:\Users\MMH\PycharmProjects\untitled\venv\lib\site-packages\bluetooth\msbt.py", line 96, in connect
    bt.connect (self._sockfd, addr, port)
OSError: A

**Comment by charlamenan** [comment]
Hi muzamilhuss,

Did you get this working ,i am looking for same solution .
I would want to automate scanning and pairing of bluetooth headset in windows 10 .

**Comment by charlamenan** [comment]
@muzamilhuss Did you get this working ?

**Comment by muzamilhuss** [comment]
@chalamenan i found another way to connect with a Bluetooth device its very simple.. you can you serial module instead of pybluez..

**Comment by BinaryBreaker** [comment]
> @charlamenan  Did you get this working ?
 i found another way to connect with a Bluetooth device its very simple.. you can use serial module instead of pybluez..

**Comment by charlamenan** [comment]
> > @charlamenan  Did you get this working ?
> > i found another way to connect with a Bluetooth device its very simple.. you can use serial module instead of pybluez..

@muzamilhuss ,Thanks for the reply .
I want to scan bluetooth devices and pair a device in windows10 .
The bluetooth device is a bluetooth headset or bluetooth speaker ,i would like only up to connection ,no need of sending message and receiving message .Can you please send example code since you have it already working for scanning and pairing part .Meanwhile i will go through the serial module .

**Comment by charlamenan** [comment]
@muzamilhuss ,can i contact you through email.My email is charlamenan@gmail.com ,please provide yours .

**Comment by BinaryBreaker** [comment]
> @charlamenan i have sent you a mail

**Comment by ghost** [comment]
Hi did you succeded installing pybluez? I installed all the dependencies but I get multiple errors from the prompt:
 LINK : fatal error LNK1181: non Š possibile aprire il file di input 'Irprops.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1

**Comment by charlamenan** [comment]
Hi ,
Yes ,i could install with python3.7.4 and windows 10 .
with python3.8 version i get error during installation

**Comment by ghost** [comment]
Hi,
Thank you for your reply. I have installed python 3.7.4 and I think I
installed all the dependencies but there is still something wrong.
I attached a screenshot of all the programs I installed for pybluez just to
show you and maybe you can notice something is missing.
Best regards

**Comment by prusswan** [comment]
For "OSError: A" error on Python 3.7, I went back to 0.22 (do not use 0.23). Someone recommended building from latest master, that works too. So the conclusion is that 0.23 release is bad for Windows/Python 3.7

**Comment by prusswan** [comment]
For "OSError: A" error on Python 3.7, I went back to 0.22 (do not use 0.23 - see #349). Someone recommended building from latest master, that works too. So the conclusion is that 0.23 release is bad for Windows/Python 3.7
