### ISSUE TITLE
Trying to connect HC-05 arduino bluetooth using pybluez and this happens?

### ISSUE THREAD

**Issue by BinaryBreaker** [pybluez/pybluez#340]
I have been trying to connect my hc 05 bt module with my laptop and to achieve a communication with Idle.

At first i connected my bt device manually from laptop's bluetooth settings and then I was able to get the module's bt address by using the following code:

import bluetooth

target_name = "HC-05"
target_address = None

nearby_devices = bluetooth.discover_devices()

for bdaddr in nearby_devices:
 if target_name == bluetooth.lookup_name( bdaddr ):
    target_address = bdaddr
    break

if target_address is not None:
  print "found target bluetooth device with address ", target_address
else:
  print "could not find target bluetooth device nearby"
I received the bluetooth address as "98:D3:31:70:7D:2D"

Now i wrote the following code to connect HC-05 via python..

bd_addr = "98:D3:31:70:7D:2D"

port = 20
sock=bluetooth.BluetoothSocket( bluetooth.RFCOMM )
sock.connect((bd_addr, port))
sock.send("1")

sock.close()
Now i browse through my laptop's bluetooth comm port settings and found 2 things 1st...

COM19 
Direction--- Incoming... 
Name--- HC-05
2nd...

COM20
Direction--- Outgoing

...
Name--- HC-05 'Dev B'
Hence I chose COM20 as I want to transmit data from Python.

When I run this code i get error:

Traceback (most recent call last):
  File "C:\Python27\TestBluetooth.py", line 26, in <module>
    sock.connect((bd_addr, port))
  File "C:\Python27\lib\site-packages\bluetooth\msbt.py", line 72, in connect
    bt.connect (self._sockfd, addr, port)
IOError: A socket operation failed because the destination host was down.
I tried both COM19 and COM20 but got the same error. My Bluetooth is connected via TX pin to arduino's RX pin and the arduino is connected to my PC so there is no error of COM port sharing that occurs sometimes.

Also when I connect my bluetooth module with laptop bluetooth and open Bluetooth Serial terminal and transmit data from there it works fine. So there's some problem in my understanding and writing of Python code. Please help...

**Comment by rgov** [comment]
Please don't overwrite the issue template because it contains important questions. For instance, you just say you're connecting from "your laptop" but you didn't mention that it is a Windows laptop. What version of Windows? What version of PyBluez?

There have been a lot of issues coming from Windows users so unfortunately it sounds like PyBluez might just be broken. PyQt also allows Python code to connect to Bluetooth.
