### ISSUE TITLE
Example script gives error

### ISSUE THREAD

**Issue by laksh225** [pybluez/pybluez#344]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:*Ubuntu 20.04*
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **Python Version:*3.8.2*
 - **PyBluez Version:*0.23*

## Issue

The example code for rfcomm-server gives error.. 

Traceback (most recent call last):
  File "/home/laksh/.local/lib/python3.8/site-packages/bluetooth/bluez.py", line 271, in advertise_service
    _bt.sdp_advertise_service (sock._sock, name, service_id, \
_bluetooth.error: (2, 'No such file or directory')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rfcomm-server.py", line 20, in <module>
    bluetooth.advertise_service(server_sock, "SampleServer", service_id=uuid,
  File "/home/laksh/.local/lib/python3.8/site-packages/bluetooth/bluez.py", line 275, in advertise_service
    raise BluetoothError (*e.args)
bluetooth.btcommon.BluetoothError: [Errno 2] No such file or directory

**Comment by ghost** [comment]
possible duplicate with https://github.com/pybluez/pybluez/issues/161 ?

**Comment by laksh225** [comment]
Ohh. Yes it is.. Thanks.

**Comment by adityasharma-tech** [comment]
After starting `bluetoothd` with `compat` flag. Everything is fine.
```bash
sudo bluetoothd --nodetach --debug --compat
```
