### ISSUE TITLE
pybluez support for python3.8.X version 

### ISSUE THREAD

**Issue by charlamenan** [pybluez/pybluez#348]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** windows10
 - **Python Version:** python 3.8.3
 - **PyBluez Version:**PyBluez-0.23

## Issue
pip install pybluez gives the following error 
Collecting pybluez
  Using cached PyBluez-0.23.tar.gz (97 kB)
Using legacy setup.py install for pybluez, since package 'wheel' is not installed.
Installing collected packages: pybluez
    Running setup.py install for pybluez ... error
    ERROR: Command errored out with exit status 1:

**Comment by charlamenan** [comment]
pybluez installation works with python3.7.4 version ,but i wanted it on python3.8.X versions .
could somebody help me please ?

**Comment by rgov** [comment]
Try `pip install wheel` and then try again.

**Comment by charlamenan** [comment]
After installing ,different issue is seen.can i get a .whl file for python3.8.X version .

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000213813AA160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))': /simple/pybluez/
**ERROR: Could not find a version that satisfies the requirement pybluez (from versions: none)
**ERROR: No matching distribution found for pybluez****

**Comment by charlamenan** [comment]
@rgov ,Wheel is given for download that supports 3.7 version  https://pypi.org/project/PyBluez/#files
Can i get wheel for download that supports python 3.8 version

**Comment by ricardoV94** [comment]
Reopening to mirror request from @charlamenan

**Comment by sanjayv2002** [comment]
pybluez seems to be simple when it comes to implementation. Is there any alternatives for interfacing bluetooth devices using python?

**Comment by rgov** [comment]
Qt for Python (formerly? alternatively? known as PyQt) does: https://doc.qt.io/qtforpython/examples/example_bluetooth__heartrate_game.html

**Comment by dogtopus** [comment]
>pybluez seems to be simple when it comes to implementation

Actually there are quite a lot of things that makes it unnecessarily complicated to maintain in the long term (Bluetooth stack being highly OS-dependent without a clear common-ground interface being one)

If one system is the only thing you target then write something just for that OS should be easy enough, pure Python (possibly with FFI/pyobjus/pyjnius) or not.

**Comment by sanjayv2002** [comment]
> Qt for Python (formerly? alternatively? known as PyQt) does: https://doc.qt.io/qtforpython/examples/example_bluetooth__heartrate_game.html

This seems like the thing I was looking for. I was looking for a way to read data from a Bluetooth device using python. (cuz I need to do lots of processing on the said data). Feel free to put suggestions guys for this task, Thanks in advance 

And I will try both of your suggestions as well. @dogtopus  and @rgov
