### ISSUE TITLE
Cant set dependencies for Raspberry Pi Zero with armv6 processor

### ISSUE THREAD

**Issue by control-led** [pybluez/pybluez#351]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Raspberry Pi Zero:**
 - **armv6
 - **python3.7**
 - **pybluez-0.23**

## Issue

Hello, 
I tried to set the dependencies with (sudo python3 setup.py install) with my raspberry pi zero armv6, but there is an error when building the bluetooth extension. 
![armv6_problem_settings_dependencies](https://user-images.githubusercontent.com/49287223/85338979-862ea080-b4e3-11ea-8f64-3236958edf2e.jpg)

With the raspberry pi 3 and armv7 the dependencies are set.
![armv7_no_problem_dependencies](https://user-images.githubusercontent.com/49287223/85338999-8dee4500-b4e3-11ea-9c29-a56000c5f8b1.jpg)

For  "import bluetooth" in python I need to extract the PyBluez-0.30-py3.7-linux-armv7l.egg file.
Otherwise the imporaation of the "bluetooth module" doesnt work.

Greetings

**Comment by ghost** [comment]
Try installing the bluetooth headers with:
`sudo apt-get install libbluetooth-dev`
