### ISSUE TITLE
How do you guys pronounce pybluez??

### ISSUE THREAD

**Issue by pkapt** [pybluez/pybluez#352]
Do you pronounce it "Pie Blues" or do you pronounce it "Pie Blue Zee"??

**Comment by ukBaz** [comment]
The BlueZ bit of it was discussed on the developers mailing list:

https://marc.info/?l=linux-bluetooth&m=153934778120279&w=2

> > So:
> > - is it "blues" like the music genre,
> > - or "blue" "zee" (like the color and a "bee")
> > - or something else?

> Most of us use the second form, though Ive seem people using the first
> form perhaps it 'sounds' better them :D
