### ISSUE TITLE
revc sometimes gets stuck 

### ISSUE THREAD

**Issue by zlj-zz** [pybluez/pybluez#357]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** linux
 - **Hardware:**  Raspberry Pi
 - **Python Version:** 3.7
 - **PyBluez Version:** 0.23

## Issue

```python
while file_len != 0:
    try:
        data = client_sock.recv(buffer)
   except bluetooth.BluetoothErrora as e:
        print(e)
        break
        f.write(data)
       file_len -= len(data)
```

I accept a file on the Raspberry Pi, about 6 M in size. In the process of receiving `recv` is easy to get stuck, I am sure there is data continue to be sent. Can you  help me?

**Comment by ukBaz** [comment]
Are you trying to transfer a file?  This would be better done with the [Object Push Profile](https://www.bluetooth.com/specifications/profiles-overview/)?

There is some more information on how to do this at:
https://raspberrypi.stackexchange.com/a/114187/121848

**Comment by zlj-zz** [comment]
thank you，i'll try it.
