### ISSUE TITLE
OSX 10.15.5, PyBlueZ, Python 3.7.3

### ISSUE THREAD

**Issue by scgrant327** [pybluez/pybluez#361]
Code:
```
import bluetooth

nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, flush_cache=True, lookup_class=False)
print("Found {} devices.".format(len(nearby_devices)))

for addr, name in nearby_devices:
    print("  {} - {}".format(addr, name))
```

Traceback (most recent call last):
  File "testBt.py", line 3, in <module>
    nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, flush_cache=True, lookup_class=False)
  File "/Users/owner/Library/Python/3.7/lib/python/site-packages/bluetooth/macos.py", line 12, in discover_devices
    devices = lightblue.finddevices(getnames=lookup_names, length=duration)
  File "/Users/owner/Library/Python/3.7/lib/python/site-packages/lightblue/_lightblue.py", line 48, in finddevices
    inquiry.run(getnames, length)
  File "/Users/owner/Library/Python/3.7/lib/python/site-packages/lightblue/_lightblue.py", line 348, in run
    err, "Error starting device inquiry")
lightblue._lightbluecommon.BluetoothError: [Errno -536870174] Error starting device inquiry

Why? What's wrong?

**Comment by scgrant327** [comment]
Code:
```
import bluetooth

nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, flush_cache=True, lookup_class=False)
print("Found {} devices.".format(len(nearby_devices)))

for addr, name in nearby_devices:
    print("  {} - {}".format(addr, name))
```

**Comment by boaz-warshawsky** [comment]
I am also experiencing the same issue, any thoughts here? 
My error is:
`ModuleNotFoundError: No module named 'lightblue'`

**Comment by networkextension** [comment]
install python-lightblue
$pip3 install python-lightblue

**Comment by boaz-warshawsky** [comment]
Thanks @networkextension, **that** problem is resolved.

**Comment by payasparab** [comment]
> Thanks @networkextension, **that** problem is resolved.
This worked for me

https://stackoverflow.com/a/74639096
