### ISSUE TITLE
Does pybluez support ble? Does pybluez support ble on windows

### ISSUE THREAD

**Issue by YunMengs** [pybluez/pybluez#373]
I saw a ble in the official example, but I didn't run successfully. Do I need Linux?

**Comment by xloem** [comment]
Looking at the source, it looks like the ble support is a partial import of libgatt.  Most of the libgatt functionality is in submodules and is left out.  There's a good list of projects at https://github.com/ukBaz/python-bluezero/wiki

**Comment by xloem** [comment]
@stale here closing this issue is the right thing to do, but the `wontfix` label is not correct.
it would be better if you would accept community commands on what to do to the issue.

**Comment by xloem** [comment]
@stale !!!!! sorry, i made things worse by talking to you.  reminder to self: DO NOT REPLY TO STALE WHEN THEY MARK THE ISSUE FOR CLOSURE.
