### ISSUE TITLE
Why I can't find BLE Devices at Raspiberry4b+?

### ISSUE THREAD

**Issue by wsysx123** [pybluez/pybluez#374]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:Raspbian 
 - **Hardware: Raspberry Pi 4b+
 - **Python Version:3.7.3
 - **PyBluez Version:0.23

## Issue

I Run Code by Command.This is the picture.Why the length is always 0?
![image](https://user-images.githubusercontent.com/30425757/99899499-c5f0f280-2ce4-11eb-92de-d402c3308248.png)

**Comment by dariussullivan** [comment]
Those processes `bluetoothctl` and `python3` are stopped, not killed. Are you trying to use CTRL+Z to quit? That leaves `bluetoothctl` still running, maybe with the device still open. Type `fg` and they will resume.

Use CTRL+D to quit instead.

**Comment by wsysx123** [comment]
I have understood this problem because my device is BLE, not bluetooth, and needs to use different search commands. thank you very much!
