### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by project-jj** [pybluez/pybluez#384]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System: Win 10
 - **Hardware: Samsung Notbook
 - **Python Version: 3.5
 - **PyBluez Version: 0.23

## Issue

(pybluez0.23) PS C:\Workspace\VSCode> & c:/Workspace/VSCode/pybluez0.23/Scripts/python.exe c:/Workspace/VSCode/pybluez0.23/client.py
No device specified. Searching all nearby bluetooth devices for the SampleServer service...
Traceback (most recent call last):
  File "c:/Workspace/VSCode/pybluez0.23/client.py", line 19, in <module>
    service_matches = bluetooth.find_service(uuid=uuid, address=addr)
  File "C:\Workspace\VSCode\pybluez0.23\lib\site-packages\bluetooth\msbt.py", line 243, in find_service
    dresults = bt.find_service (addr, uuidstr)
OSError

![0 23 error](https://user-images.githubusercontent.com/77441392/104590984-6ba25b80-56af-11eb-883e-66634364873a.png)

**Comment by lshaf** [comment]
I have similar issue on find_service and connect when using windows.
But it has no problem when I'm using linux on my raspi.

![image](https://user-images.githubusercontent.com/4636265/107239775-c5eace00-6a5b-11eb-8f29-5f35b4b06a46.png)
