### ISSUE TITLE
pybluez discover_devices returns an empty list - raspberry pi zero 

### ISSUE THREAD

**Issue by MegaRusher** [pybluez/pybluez#394]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:** Linux happy 5.10.17 - raspios buster
 - **Hardware:** Raspberry Pi Zero - armv6l + embedded BT (B8:27:EB:59:73:88)
 - **Python Version:** Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
 - **PyBluez Version:** PyBluez-0.23-cp37-cp37m-linux_armv6l.whl
 -  Controller: B8:27:EB:59:73:88  my BT Hardware .... could be useful =)

## Issue
The method discover_devices() returns an empty list on my raspberry pi zero.
Tried also with root user (in case of any rights problem) but it's still empty.

I can perform everything with the normal pi user and bluetoothctl + a complex expect script,
but i'd prefer a 100% Pythonic way.

Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
>>> import bluetooth
>>> bluetooth.discover_devices()
[]

Well that's it, too bad that i cannot use your library.
Thanks for reading, cheers
Manu

**Comment by artemgordinskiy** [comment]
@MegaRusher I'm facing the exact same issue, except on Pi3. Have you ever been able to get to the bottom of this?

Too bad this issue got no attention.

**Comment by schodet** [comment]
It seems that a user of NXT-Python has the same issue: https://github.com/schodet/nxt-python/issues/175

**Comment by dogtopus** [comment]
#404
