### ISSUE TITLE
Not working on macos bigsur -`Cannot load LightAquaBlue framework`

### ISSUE THREAD

**Issue by viral-sangani** [pybluez/pybluez#397]
## System

 - MacOS BigSur - Version 11.2.3
 - **Hardware:** internal macbook bluetooth
 - **Python version** - 3.8.2
 -  **pybluez version** - 0.23 Latest

## Issue

I have created a new virtual env. and tried installing pybluez via `pip install --upgrade git+https://github.com/karulis/pybluez.git#egg=pybluez` this command. Installation is completed without any error but when tried to import is shows the following error.

```
ImportError: Cannot load LightAquaBlue framework, not found at /Users/viralsangani/Desktop/Projects/
opensource/venv/lib/python3.8/site-packages/lightblue/LightAquaBlue.framework
```
I tried installing LightAquaBlue from the source but it's showing an error while installing.

**Comment by sensiblepuffin** [comment]
I had some success with installing lightblue from [here](https://github.com/0-1-0/lightblue-0.4), which installs LightAquaBlue to /Library/Frameworks/, and then copying /Library/Frameworks/LightAquaBlue.framework/ into the site-packages directory (beware, it's all links).

**Comment by bwomsm1** [comment]
Hi, I am also facing this issue, I am currently using pybluez version 0.30, with Mac big Sur.
Any advice?
