### ISSUE TITLE
PyBluez package dependency without any platform marker. Cannot add pybluez using Poetry

### ISSUE THREAD

**Issue by sisco70** [pybluez/pybluez#399]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:**  Linux Ubuntu 20.04.2 LTS
 - **Hardware:** (external Bluetooth adaptor,)
 - **Python Version:** 3.8.5
 - **PyBluez Version:** Latest

## Issue
**Package manager Poetry cannot add pybluez package from PyPi on Linux Ubuntu**  

Poetry is reading the dependencies for a current version of a package from PyPi's API.   
In case of pybluez, this is here: https://pypi.org/pypi/PyBluez/json

As you can see pyobjc-core is listed under requires_dist without any platform marker. Which is wrong.

**Comment by mrkeuz** [comment]
Same issue. Workaround:
https://github.com/python-poetry/poetry/issues/3415#issuecomment-812666342
