### ISSUE TITLE
Works on Android? 

### ISSUE THREAD

**Issue by Hunter2809** [pybluez/pybluez#417]
## System

 - **Operating System:** NA
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.) NA
 - **Python Version:** 3.9
 - **PyBluez Version:** NA

## Issue
Hey! 

So I am trying to capture the packets sent by the Bluetooth devices to my Android Mobile. So how I am thinking to achieve this, is to first connect the device to my Windows PC, test and debug the application if I am successful to make it, and then pack it in an apk. 

So is there a way to make this module work with Android Bluetooth? I know it's a bit weird, but would be glad if there's a work around or something!

**Comment by dogtopus** [comment]
No it doesn't. However it should be possible to implement it via JNI (i.e. calling the Android Bluetooth API). PRs welcome.
