### ISSUE TITLE
how to detect bluetooth connect status?

### ISSUE THREAD

**Issue by liuzhijun23** [pybluez/pybluez#419]
I use pybluez on windows 10.The PC can accept the bluetooth connection from my phone.But how to detect the connect status if the phone disconnect the bluetooth?I want to get the disconnect status/event.Please help.

**Comment by dogtopus** [comment]
IIRC I used asyncio's Protocol.connection_lost event with socket client and it just worked. So I assume (without asyncio) it should just work like any other stream sockets.
