### ISSUE TITLE
Raspberry pi use bluetooth.discover_devices api duration’s value can‘t over 48

### ISSUE THREAD

**Issue by kxy09** [pybluez/pybluez#420]
## System

 - **Operating System: Raspbian 10 buster**
 - **Hardware: Raspberry Pi 3B** 
 - **Python Version: 3.7.3**
 - **PyBluez Version: 0.23**

## Issue

If the duration value exceeds 48 seconds, an error will be reported
---------------------------------------------------------------------------------------------------------------------------------
root@raspberrypi:~/bl# python3 scan.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bluetooth/bluez.py", line 25, in discover_devices
    iac=iac)
_bluetooth.error: (22, 'Invalid argument')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scan.py", line 5, in <module>
    nearby_devices = bluetooth.discover_devices(duration=49,lookup_names=False)
  File "/usr/local/lib/python3.7/dist-packages/bluetooth/bluez.py", line 29, in discover_devices
    "bluetooth adapter: " + e.args[1])
bluetooth.btcommon.BluetoothError: [Errno 22] Error communicating with local bluetooth adapter: Invalid argument

**Comment by dogtopus** [comment]
This is likely a limit set in the Bluez stack. If you want continuous scanning you could probably use a loop that do scans back to back.
