### ISSUE TITLE
How to enable / subscribe to characteristic notifications?

### ISSUE THREAD

**Issue by bofetadas** [pybluez/pybluez#422]
## System

 - **Operating System:**: Ubuntu 18.04
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.): Lenovo E490
 - **Python Version:**: 3.6.9
 - **PyBluez Version:** 0.23

## Issue

I'd like to connect my Laptop to a peripheral device to wait for changes on a certain characteristic. I know how to connect to the device and I've also seen example code how to deal with notifications for example [here](https://github.com/oscaracena/pygattlib/blob/master/examples/receive_notification.py) and [here](https://github.com/peplin/pygatt) but I couldn't find any documentation about how to enable notifications/subscribing to characteristic changes.

Can anybody point me into the right direction here?

**Comment by hiaselhans** [comment]
i think pybluez isn't the first address for BLE.
maybe give [bleak](https://github.com/hbldh/bleak) a try?
