### ISSUE TITLE
pybluez with python 3.10 requires PY_SSIZE_T_CLEAN macro in # format

### ISSUE THREAD

**Issue by rudyvan** [pybluez/pybluez#426]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - Debian bullseye (11)
 - Raspberry Pi, external Bluetooth adaptor
 - python 3.10.0
 - pybluez version: latest

## Issue

pybluez needs update for python 3.10 as then it requires PY_SSIZE_T_CLEAN macro in # format
From version 3.10 of python, the interface to C programs must be in this specific format

if you run below script, as of 3.10 you get a system error:

```
bluez.hci_send_cmd(self.btle_sock, OGF_LE_CTL, OCF_LE_SET_SCAN_ENABLE, cmd_pkt)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by axilirator** [comment]
Can we please have a patch release containing this fix? Thanks!

**Comment by kred-jon** [comment]
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

Python 3.10.4

Ubuntu 22.04 LTS
