### ISSUE TITLE
Cannot open input file 'Irprops.lib'

### ISSUE THREAD

**Issue by PFloyd0** [pybluez/pybluez#436]
*PyBluez is not under active development but we are seeking new contributors
to investigate bugs and submit patches.*

## System

 - **Operating System:Windows
 - **Hardware:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **Python Version:3.8
 - **PyBluez Version:**

## Issue

When I try to install the PyBluez using pip, there are some errors:

      LINK : fatal error LNK1181: cannot open input file 'Irprops.lib'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed
 with exit code 1181

Is there any solution? Thank you!

**Comment by SaidTorres3** [comment]
In the setup.py file of this library, search "Irprops" and change it to "bthprops", then, install it.

I had this exact problem and it worked.

**Comment by takeraparterer** [comment]
> bthprops

you're a lifesaver tysm
