### ISSUE TITLE
error in PyBluez setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by johanjohan** [pybluez/pybluez#446]
on raspberry pi 3, 
Python 3.10.0, 
setuptools 62.0.0
Using cached PyBluez-0.23.tar.gz

EDIT:
I could fix it, installing from source: PyBluez==0.30

**Comment by cimm** [comment]
Just a quick note since this is the first issue I found when debugging the same error message and @dogtopus [suggestion](https://github.com/pybluez/pybluez/issues/431#issuecomment-1107884273) seems to work.

**Comment by Kronodile** [comment]
@johanjohan could you elaborate how you fixed it?

**Comment by johanjohan** [comment]
@Kronodile i followed the instructions on https://github.com/pybluez/pybluez/blob/master/docs/install.rst

<html><body>
<p dir="auto"><strong>Installing PyBluez from source</strong></p>
<p dir="auto">Download a stable release from <a href="https://github.com/pybluez/pybluez/releases">https://github.com/pybluez/pybluez/releases</a></p>
<p dir="auto">or download the latest version using the links below.</p>


master.zip | master.tar.gz
-- | --



<p dir="auto">Extract the zip or tar and cd to the extracted file directory, then:</p>
<pre>python setup.py install
</pre>
<p dir="auto">for Bluetooth Low Energy support (GNU/Linux only):</p>
<pre>pip install -e .[ble]
</pre>
</body>
</html>Installing PyBluez from source

**Comment by Kronodile** [comment]
> @Kronodile i followed the instructions on https://github.com/pybluez/pybluez/blob/master/docs/install.rst
> 
> **Installing PyBluez from source**
> 
> Download a stable release from https://github.com/pybluez/pybluez/releases
> 
> or download the latest version using the links below.
> 
> master.zip	master.tar.gz
> Extract the zip or tar and cd to the extracted file directory, then:
> 
> python setup.py install
> for Bluetooth Low Energy support (GNU/Linux only):
> 
> pip install -e .[ble]
> Installing PyBluez from source

Thanks!

What's PyBluez==0.30 though?

**Comment by Plaque-fcc** [comment]
> What's PyBluez==0.30 though?

This is how you choose a specific version of the package.
