### ISSUE TITLE
Question - discovering devices with their addresses

### ISSUE THREAD

**Issue by arezazadeh** [pybluez/pybluez#470]
Hi all,

Is there any way I can discover devices with their addresses assuming i have their addresses? since smartphones are not beaconing all the times, i want to know if i can discover them once they are beaconing and get their address and then i will be able to discover them again by their address. is this doable?

Thanks in advance.

Ahmad.

**Comment by dogtopus** [comment]
All you need is the BDADDR of the device and what service it's running on what channels to send messages to it. Everything else (discoverability, SDP, GATT, etc.) are optional.
