### ISSUE TITLE
Cannot Properly install with pip on M1 Macbook

### ISSUE THREAD

**Issue by Jensen-holm** [pybluez/pybluez#487]
## System

 - **Operating System:** macOs Sonoma 14.1.1
 - **Python Version:** 3.10.13
 - **PyBluez Version:** 0.23

## Issue

`virturalenv venv` <br>
`source venv/bin/activate` <br>
`pip install PyBluez` <br>

output:

Collecting PyBluez
  Using cached PyBluez-0.23.tar.gz (97 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyBluez setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mikry13** [comment]
This worked for me https://github.com/pybluez/pybluez/issues/431#issuecomment-1107884273
