### ISSUE TITLE
Example in wiki won't discover

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pybluez/pybluez#53]
```
What steps will reproduce the problem?
1. python RFCOMM\ Server.py
2. python RFCOMM\ Client.py

What is the expected output? What do you see instead?
to see the string "Hello!!" on the terminal that is running "RFCOMMServer.py", 
instead I see the failed condition string "Failed to discover FoobarService"

What version of the product are you using? On what operating system?
PyBluez 0-18.1 on Ubuntu Linux 10.04

Please provide any additional information below.
this is the page I'm following, and attached are the two files mentioned above
```

Original issue reported on code.google.com by `oday.ma...@gmail.com` on 22 Jan 2012 at 1:28

Attachments:
- [RFCOMM Client.py](https://storage.googleapis.com/google-code-attachments/pybluez/issue-53/comment-0/RFCOMM Client.py)
- [RFCOMM Server.py](https://storage.googleapis.com/google-code-attachments/pybluez/issue-53/comment-0/RFCOMM Server.py)

**Comment by karulis** [comment]
Bit old, but I think solution might be same as for issue: https://github.com/karulis/pybluez/issues/81
