### ISSUE TITLE
Problem with running RFCOMM server on  PORT_ANY on debian OS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pybluez/pybluez#57]
```
What steps will reproduce the problem?
1. run bluetooth-agent  on server host
2. rfcomm-server.py on server host
3. connect from another host using rfcomm-client.py 

What is the expected output? What do you see instead?
"Accepted connection from ..."

What version of the product are you using? On what operating system?
0.18 on Debian Wheezy (B3) using Python 2.6 or Python 2.7

Please provide any additional information below.

According the client I'm connected!:

$ python rfcomm-client.py XX:XX:XX:XX:XX:XX
Searching for SampleServer on XX:XX:XX:XX:XX:XX
connecting to "SampleServer" on XX:XX:XX:XX:XX:XX
connected.  type stuff

However, rfcomm-server.py diagrees (accept() never returns) :

$ python2.6 rfcomm-server.py 
Waiting for connection on RFCOMM channel 1
(.... Nothing)
```

Original issue reported on code.google.com by `geoff.fl...@gmail.com` on 11 Nov 2012 at 4:28

**Comment by karulis** [comment]
It seems that it is not reproducible on Ubuntu 14.04 with bluez 4.101
I will try newest stable debian

Now I can not reproduc:

> And what is interesting after fixing issue 45, in bind with local BT address and bt port any I get:
> Traceback (most recent call last):
>  File "examples/simple/rfcomm-server.py", line 10, in <module>
>    server_sock.bind(("xx:xx:xx:xx:xx:xx", PORT_ANY))
>  File "/usr/local/lib/python3.2/dist-packages/bluetooth/bluez.py", line 172, in bind
>    return self._sock.bind (addrport)
> _bluetooth.error: (98, 'Address already in use')

**Comment by karulis** [comment]
Ok on debian 8 issue does not reproduce

But in bluez 5.23 it is necessary to pass --compat option to bluetoothd to run sdptool and use 
https://github.com/karulis/pybluez/blob/master/examples/simple/rfcomm-server.py exmaple

Anyway I thing this issue has nothing to do with pybluez implementation - so closing.
