### ISSUE TITLE
pybluez Installtion on Mac

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pybluez/pybluez#63]
```
What steps will reproduce the problem?

1. Download the latest zip file(PyBluez-0.20)
2. Move to the Root directory and issue pip installor pybluez sudo easy_install 
pybluez commands
3.Installation errors in the Terminal 

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?

0.20
Mac OSX 10.9.1
Python 2.7.5

Please provide any additional information below.

Is pybluez supports Mac OS ?

```

Original issue reported on code.google.com by `imobil...@gmail.com` on 18 Feb 2014 at 7:19

Attachments:
- [pyBluezErrors.rtf](https://storage.googleapis.com/google-code-attachments/pybluez/issue-63/comment-0/pyBluezErrors.rtf)

**Comment by karulis** [comment]
Ok initial support for OSX was added by merging LightBlue source code into Publuez
Functionality is very unstable - I have added 2 issues to track problems
