### ISSUE TITLE
Support for Bluetooth Low Energy (BLE) / GATT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pybluez/pybluez#68]
```
It would be great to have wrappers for the Bluetooth Low Energy features added 
in the recent version(s) of BlueZ, to allow for the following features to be 
controlled from a python application:

 * discovery of BLE devices and their GATT services
 * reading and writing of BLE attributes/values
 * creation and management of GATT services

I am interested in contributing, but not sufficiently experienced with the 
pybluez source code to create sensible abstractions for the low-level functions.
```

Original issue reported on code.google.com by `aprsdr...@googlemail.com` on 18 Jun 2014 at 1:38
##

**Comment by karulis** [comment]
Now we have initial support for BLE on Linux platform - release 0.22

**Comment by larsblumberg** [comment]
Hi @karulis! Do I find a documentation somewhere what the state of BLE support is right now?

**Comment by ksze** [comment]
Regarding BLE support, does anybody know whether it's possible (and how) to scan for BLE beacons without root privilege using pybluez?

Currently, if I try to scan for BLE beacons as a normal user (in the "bluetooth" and "lp" unix user groups), I get a RuntimeError:
```
~ $ ipython
Python 3.6.2 | packaged by rpi | (default, Jul 19 2017, 12:58:40)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from bluetooth.ble import BeaconService

In [2]: service = BeaconService()

In [3]: service.scan(2)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-b47b2f3a4f45> in <module>()
----> 1 service.scan(2)

RuntimeError: Set scan parameters failed (are you root?)
```

**Comment by filips123** [comment]
@rgov @karulis Does BLE works on Windows 10? If not, can it be supported?

**Comment by rgov** [comment]
I believe BLE only works on Linux. There is no one currently working on the project to add support for this, unfortunately. However, you may be able to use PyQt5 and its cross-platform QBluetooth API.
