### ISSUE TITLE
How to detect PyblueZ'connection status on Windows 7

### ISSUE THREAD

**Issue by justalittlenoob** [pybluez/pybluez#80]
Hi, I have a question when working with pybluez. I have already done a project wich pybluez, which can transfer data from a bluetooth device to my computer. But, there is something not perfect that i cannot detect the status of the connection of bt device and computer. I have look through all the API http://pybluez.googlecode.com/svn/www/docs-0.7/index.html, it seems that the only way to detect the status of the connectin is use settimeout function which is only worked on linux/GNU, but my project is based on windows 7. what should i do? Any advices will be appreciat. Thank you.

**Comment by karulis** [comment]
Discussion on groups.google.com:
https://groups.google.com/forum/#!topic/pybluez/lkNk9bI2Ji0

please let me know if it helps
