### ISSUE TITLE
advertise_service() uncorrectly work in some condition.

### ISSUE THREAD

**Issue by youngbo89** [pybluez/pybluez#92]
advertise_service() uncorrectly work in certain condition.
- Host computer has serveral bt devices &&
- The socket which we want to advertise is bound to specific device &&
- The device is un-advertisable.

A couple of days ago, I already mentioned this bug.

https://groups.google.com/forum/#!topic/pybluez/al8MDolLBd0

Thanks for replying  :-)

**Comment by karulis** [comment]
Hi and thanks for report and great pull request:)

I just have one question - when the device is un-advertisable?

**Comment by youngbo89** [comment]
I consider these state :
- No device
- No up
- No running
- No iscan
- No pscan

In addition, I found out that these state can be read from flags in "struct hci_dev_info" using ioctl().

**Comment by karulis** [comment]
Thanks:)
I have tested it and it works fine:)
Will be included in release 0.23

**Comment by karulis** [comment]
Merged
