### ISSUE TITLE
python3.5 deprecated API warnings

### ISSUE THREAD

**Issue by karulis** [pybluez/pybluez#96]
Lots of deprecated API warnings when building for python 3.5

msbt_msbt.c(170): warning C4996: 'WSAStringToAddressA': Use WSAStringToAddressW() instead or define _WINSOCK_DEPRECATED
_NO_WARNINGS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(3623): note: see declaration of 'WSAStringToAddressA'
msbt_msbt.c(241): warning C4996: 'WSAStringToAddressA': Use WSAStringToAddressW() instead or define _WINSOCK_DEPRECATED
_NO_WARNINGS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(3623): note: see declaration of 'WSAStringToAddressA'
msbt_msbt.c(358): warning C4996: 'WSADuplicateSocketA': Use WSADuplicateSocketW() instead or define _WINSOCK_DEPRECATED
_NO_WARNINGS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(2872): note: see declaration of 'WSADuplicateSocketA'
msbt_msbt.c(365): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to di
sable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(3457): note: see declaration of 'WSASocketA'
msbt_msbt.c(479): warning C4996: 'WSAStringToAddressA': Use WSAStringToAddressW() instead or define _WINSOCK_DEPRECATED
_NO_WARNINGS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(3623): note: see declaration of 'WSAStringToAddressA'
msbt_msbt.c(585): warning C4996: 'WSALookupServiceBeginA': Use WSALookupServiceBeginW() instead or define _WINSOCK_DEPR
ECATED_NO_WARNINGS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(3693): note: see declaration of 'WSALookupServiceBeginA'
msbt_msbt.c(607): warning C4996: 'WSALookupServiceNextA': Use WSALookupServiceNextW() instead or define _WINSOCK_DEPREC
ATED_NO_WARNINGS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(3752): note: see declaration of 'WSALookupServiceNextA'
msbt_msbt.c(720): warning C4996: 'WSASetServiceA': Use WSASetServiceW() instead or define _WINSOCK_DEPRECATED_NO_WARNIN
GS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(4157): note: see declaration of 'WSASetServiceA'
msbt_msbt.c(775): warning C4996: 'WSASetServiceA': Use WSASetServiceW() instead or define _WINSOCK_DEPRECATED_NO_WARNIN
GS to disable deprecated API warnings
C:\Program Files (x86)\Windows Kits\8.1\include\um\winsock2.h(4157): note: see declaration of 'WSASetServiceA'
##

**Comment by beadysea** [comment]
I get the same warnings on Windows 10 with Python 3.6 and 3.7. Seems to be changes in winsock2 between windows 7 and windows 8.1 releases. 
[Compatibility Win7.0 to Win8.1](https://abi-laboratory.pro/compatibility/Windows_7.0_to_Windows_8.1/x86_64/headers_diff/ws2_32.dll/diff.html)
Looking around the net, the easy is to just ignore the compiler warnings by adding
 `#define _WINSOCK_DEPRECATED_NO_WARNINGS`
before `#include <winsock2.h>` in _msbt.c
A simple fix however if we do this I think it's important to comment the offending lines with todo's. Compilation warnings are there for a reason after all.

**Comment by rgov** [comment]
There is a branch, https://github.com/pybluez/pybluez/tree/issue_96, where this was worked on previously. You can see the diff here: https://github.com/pybluez/pybluez/compare/issue_96?expand=1

I'm not sure what the status is.
